title       = "wolframfns"
baseURL     = "https://wolframfns-cli.tamnd.com/"
description = "A command line for wolframfns."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/wolframfns-cli"
